name: Dummy CI

on:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [dev-tools, domain, infra, app]
    steps:
      - name: Checkout
        run: echo 'dummy job was success'
